package numberGuessingGame;

import java.util.*;
import javax.swing.*;
import java.awt.event.*;
class Game
{
 JFrame f= new JFrame();
 int attempt=6;
 Random r=new Random();
 int input;
 boolean round2res=true;
 boolean round3res=true;
 int score=0;
 int totscore=0;
 Game()
 {
 JOptionPane.showMessageDialog(null,"GUESS THE NUMBER GENERATED BY THE COMPUTER. THERE ARE TOTALLY THREE ROUNDS.\n IN EACH ROUND YOU HAVE 6 ATTEMPTS TO FIND THE NUMBER.");
 }
 void labelfunction(String a)
 {
 JLabel instruct = new JLabel(a);
 instruct.setBounds(200,70,850,40);
 f.add(instruct);
 }
 void game(int n1,String roundinstruct)
 {
 f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 labelfunction(roundinstruct);
 JLabel number=new JLabel("ENTER A NUMBER");
 f.add(number);
 number.setBounds(200,155,100,30);
 JTextField tf=new JTextField();
 tf.setBounds(325,155,150,35);
 f.add(tf);
 JButton but=new JButton("SUBMIT");
 but.setBounds(190,275,125,40);
 f.add(but);
 but.addActionListener(new ActionListener()
 {
 public void actionPerformed(ActionEvent q)
 {
 attempt-=1;
 String temp=tf.getText();
 input=Integer.parseInt(temp);
 if (n1==input)
{
 JOptionPane.showMessageDialog(null,"YOU GUESSED THE NUMBER!!!! THE GENERATED NUMBER IS "+n1);
 score=attempt+1;
attempt=6;
f.getContentPane().removeAll();
 f.getContentPane().repaint();
 f.dispose();
 if (round2res==true)
 {
 JOptionPane.showMessageDialog(null,"YOU PASSED ROUND 1!!!! \n YOUR SCORE "+score*10);
 totscore+=score*10;
round2();
 }
else if (round2res==false && round3res==true)
 {
 totscore+=score*10;
JOptionPane.showMessageDialog(null,"YOU PASSED ROUND 2!!!! \n YOUR SCORE "+score*10);
 round3();
 }
else if(round2res==false && round3res==false)
 {
 totscore+=score*10;
JOptionPane.showMessageDialog(null,"CONGRATULATIONS!!!!!! YOU SUCCESSFULLY COMPLETED THE GAME WITH A TOTAL SCORE OF "+totscore);
 }
 }
if (attempt==0)
 {
 JOptionPane.showMessageDialog(null,"GAME OVER!!! THE GENERATED NUMBER IS "+n1);
 JOptionPane.showMessageDialog(null,"YOUR TOTAL SCORE IS "+totscore);
 System.exit(0);
 }
if (input<n1)
{
 JOptionPane.showMessageDialog(null,"THE ENTERED NUMBER IS LESS THAN THE GENERATED NUMBER\nATTEMPTS LEFT : "+attempt);
 }
if(input>n1)
{
 JOptionPane.showMessageDialog(null,"THE ENTERED NUMBER IS HIGHER THAN THE GENERATED NUMBER\n ATTEMPTS LEFT : "+attempt);
 }
tf.setText("");
 }
 }
 );
 JButton exit=new JButton("EXIT");
 exit.setBounds(360,275,125,40);
 f.add(exit);
 exit.addActionListener(new ActionListener()
 {
 public void actionPerformed(ActionEvent q)
 {
 System.exit(0);
 }
 }
 );
 f.setTitle("Guessing Game");
 f.setSize(750,500);
 f.setLayout(null);
 f.setVisible(true);
 }
 void round1()
 {
 JOptionPane.showMessageDialog(null,"ROUND-1: THIS ROUND HAS NUMBERS BETWEEN 1 AND 50");
 int num1=r.nextInt(50);
 game(num1,"THIS ROUND HAS NUMBERS BETWEEN 1 AND 50");
 }
 void round2()
 {
 int num2=r.nextInt(100);
 JOptionPane.showMessageDialog(null,"ROUND-2: THIS ROUND HAS NUMBERS BETWEEN 1 AND 100");
 f.setTitle("ROUND-2");
 round2res=false;
 game(num2,"THIS ROUND HAS NUMBERS BETWEEN 1 AND 100");
 }
 void round3()
 {
 int num3=r.nextInt(200);
 JOptionPane.showMessageDialog(null,"ROUND-3: THIS ROUND HAS NUMBERS BETWEEN 1 AND 200");
 f.setTitle("ROUND-3");
 round3res=false;
 game(num3,"THIS ROUND HAS NUMBERS BETWEEN 1 AND 200");
 }
}
class main
{
 public static void main(String args[])
 {
 Game g=new Game();
 g.round1();
 }
}